### PR TITLE
Node v6.11.3

### PR DESCRIPTION
**Pull request by huseyinkozan**
Cleaned libicu and updated to Node 6.11.3.

### CODE REVIEW

**Comment by HipsterBrown** [comment]
@huseyinkozan Why was libicu removed? Is that something that changed with Node 6?

**Comment by huseyinkozan** [comment]
I added libicu for a `intl` build, but node is not using it. Node 6 runs without `intl` support.

**Comment by HipsterBrown** [comment]
Node 6.11.2 Release Notes -> https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V6.md#6.11.2

**Comment by rwaldron** [comment]
@HipsterBrown we don't want to build with ICU either way (the deps are massive)

**Comment by rwaldron** [comment]
The only thing holding me up on this is that t2-release doesn't work as intended anymore and I'm still in the process of updating it. Aside from that, I could do it manually like we did in the last release, but I won't do that on a Friday ;)

**Comment by huseyinkozan** [comment]
There is a libicu package at master branch : https://github.com/openwrt/packages/tree/master/libs/icu. The first one that I added was not complete. 
I built it the official one with a small modification. If anyone try to integrate, I can add it to this PR.

**Comment by rwaldron** [comment]
Just to make sure I still understand correctly: We really **do not** want to ship built-in ICU data, it's too large.

**Comment by huseyinkozan** [comment]
https://github.com/nodejs/node/wiki/Intl#q-by-how-much-do-the-various-options-affect-the-on-disk-sizes
https://github.com/nodejs/node/issues/2300

I think, we dont need it

**Comment by huseyinkozan** [comment]
Actually my last trial was for enable the inspector. It depends on intl : https://github.com/nodejs/node/blob/v6.x/configure#L1291

Anyway, old fashion `console.log()` is another option

**Comment by tikurahul** [comment]
@huseyinkozan - inspector will be an amazing feature for Tessel. What are the missing pieces to enable that ?

**Comment by huseyinkozan** [comment]
@tikurahul After enable the system icu with `--with-intl=system-icu` flag, I got an error that complains about cannot find `uchar.h`

With the modified official libicu package, I got these `uchar.h` files:
```
$ find build_dir -name uchar.h
build_dir/host/icu4c-59.1/common/unicode/uchar.h
build_dir/host/icu/source/common/unicode/uchar.h
build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/node-v6.11.2/deps/icu-small/source/common/unicode/uchar.h
```
But I cannot find any CFLAG to give it a  correct path. Maybe we need to change install path, but dont know. 

The small modification is replacing `$(STAGING_DIR_HOSTPKG)` with `$(STAGING_DIR)/host`.

**Comment by huseyinkozan** [comment]
Updated to v6.11.3. Built but not write to Tessel.

**Comment by rwaldron** [comment]
I'd like to do a release next week. I will try to make the requisite time for that

**Comment by huseyinkozan** [comment]
Ok, thanks Rick.

I had also tried to build v8.4.0, but got an error about `std::nearbyint`. Just want to inform about

**Comment by rwaldron** [comment]
I've just completed a build and updated a Tessel 2 locally. My next steps are to run a few common programs (from Sparkfun and our own tutorials) on the updated Tessel 2. Once that's complete, I will do the final push. I estimate no later than Thursday

**Comment by huseyinkozan** [comment]
Ok, thanks. Ask me if I can do something.

Not related, but I am fihgting a memory issue. My project grown so much. Trying to minimize it. Any methods to decrease RAM usage ?

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

**Comment by rwaldron** [comment]
> Edit: Sorry, was a silly question. I may try profiling at computer before push it.

That was going to be my suggestion :)

**Comment by k45514n** [comment]
Does this need to be closed?

**Comment by HipsterBrown** [comment]
@nodebotanist Yes, we're now on Node 8 support. Thanks for triaging. :clap:

**Pull request closed without merging**
